package com.greentree.common.graphics.sgl.enums.gl;

import static org.lwjgl.opengl.GL30.*;

public enum GLFramebufferStatus {

	FRAMEBUFFER_COMPLETE(GL_FRAMEBUFFER_COMPLETE),
	FRAMEBUFFER_INCOMPLETE_ATTACHMENT(GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT),
	FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT(GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT),
	FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER(GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER),
	FRAMEBUFFER_INCOMPLETE_READ_BUFFER(GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER),
	FRAMEBUFFER_UNSUPPORTED(GL_FRAMEBUFFER_UNSUPPORTED),
	FRAMEBUFFER_INCOMPLETE_MULTISAMPLE(GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE),
	FRAMEBUFFER_UNDEFINED(GL_FRAMEBUFFER_UNDEFINED),
	;
	public final int glEnum;

	GLFramebufferStatus(int glEnum) {
		this.glEnum = glEnum;
	}

	public static GLFramebufferStatus get(int glEnum) {
		for(var e : values())
			if(e.glEnum == glEnum)
				return e;
		return null;
	}
}
