name: Build

on:
    push:
        branches: 
            - '*'
    pull_request:
        branches:
            - '*'
    workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        experimental: [true]
        os: [ubuntu-latest]
    runs-on:  ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
    - uses: actions/checkout@v2
      
    - uses: s4u/setup-maven-action@v1.7.0
      with:
          java-version: 21
          java-distribution: temurin
          maven-version: 3.9.5
            
    - run: mvn -v
    - run: mvn -B clean test -f Commons
