# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Show Folders
        run: ls
      - name: Show Java Version
        run: java -version
      - name: Show Maven Version
        run: mvn -v
