name: Build

on:
    push:
        branches: 
            - '*'
    pull_request:
        branches:
            - '*'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 'Set up latest Oracle JDK 21'
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 21
    - run: mvn -v
    - run: mvn -B clean test -f Commons
