name: Build

on:
  - workflow_dispatch
  push:
    branches:
      - '*'
    paths:
      - '**/src/**'
      - '**/pom.xml'
  

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
              
      - name: Maven Verify
        run: mvn -B clean verify -f Commons

  codecov:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Test Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


  sonarcloud:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Analyze with SonarCloud
#       set environment variables:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#       run sonar maven plugin:
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=antkorwin_github-actions -Dsonar.organization=antkorwin-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml
        

  
