name: Build

on:
    push:
        branches: 
            - '*'
    pull_request:
        branches:
            - '*'
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      
    # - uses: s4u/setup-maven-action@v1.7.0
    #   with:
    #       java-version: 21
    #       java-distribution: temurin
    #       maven-version: 3.9.5
            
    - name: Maven Verify
      run: mvn -B clean verify -f Commons

    - uses: actions/upload-artifact@v3
      with:
        name: main-artifact
        path: Commons/

  test-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: main-artifact

    - name: Test Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  
