name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - '**/src/**'
      - '**/pom.xml'
  

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
              
      - name: Maven Verify
        run: mvn -B clean verify -f Commons

  codecov:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Test Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


  sonarcloud:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Analyze with SonarCloud
#       set environment variables:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#       run sonar maven plugin:
        run: mvn -B verify -f Commons sonar:sonar -Dsonar.projectKey=lat-green_Commons -Dsonar.login=$SONAR_TOKEN
        

  
